name: Pylint

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        source .github/common-setup.sh
    - name: Pylint style analysis
      run: |
        echo "Running pylint on source code..."
        pylint $(git ls-files 'src/*.py') \
        --disable=missing-module-docstring \
        --disable=too-few-public-methods \
        --disable=no-self-argument \
        --disable=inconsistent-return-statements \
        --disable=too-many-arguments \
        --disable=unspecified-encoding

        echo "Running pylint on tests..."
        pylint $(git ls-files 'test/*.py') \
        --disable=missing-module-docstring \
        --disable=too-few-public-methods \
        --disable=no-self-argument \
        --disable=inconsistent-return-statements \
        --disable=too-many-arguments \
        --disable=unspecified-encoding \
        --disable=missing-function-docstring \
        --disable=missing-class-docstring \
        --disable=import-error \
        --disable=wrong-import-position
