name: Release to PyPI

# This is explicitly not runnable manually. Manual releases should be initiated locally.
on: 
  release:
    types: [published]
  push:
    branches:
      - pip

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: pypi-release
      url: https://pypi.org/project/flash-patcher/
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Install Common Dependencies
      run: |
        source .github/common-setup.sh
    - name: Build Flash Patcher
      env:
        ANTLR_TARGET: antlr-java
      run: |
        export ANTLR_TARGET=antlr-java
        cd build
        make
        cd ..
    - name: Release to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
