name: Unit Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Set up Java
    #   uses: actions/setup-java@v4.0.0
    #   with:
    #     distribution: 'adopt'
    #     java-version: '17'
    - name: Install Common Dependencies
      run: |
        source .github/common-setup.sh
    - name: Run unit tests
      run: |
        export ANTLR_TARGET=antlr-java
        cd build && make test
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: build/coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '90 90'
